[package]
name = "mkcpp"
version = "0.1.0"
edition = "2021"
authors = ["Alex Afshar <contact@alexafshar.com>"]
readme = "README.md"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
sailfish = "0.5.0"
